<a href="https://colab.research.google.com/github/nspeer12/AI_CAP4630/blob/master/hw4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

### Homework 4

# Problem 1

Using only ```numpy```, implement the function ```conv2d```.  It takes as input ```input_mat``` and ```kernel_mat``` and outputs ```output_mat```.  All variables 
are square matrices.  It should compute the convolution of ```input_mat``` with the kernel ```kernel_mat``` using valid padding.



## Convolutions
Convolutions are an operation that involve two input parameters. Firstly, an input matrix is passed, and secondly a kernel, or filter is defined. In convolutions, the kernel iterates through the columns and rows of the input matrix by a specified stride length. The regions considered are allowed to overlap. If the input, kernel, and stride length do not fit, the input matrix can be padded with zeros so the operation can be performed. The kernel iterates, and considers each subset of the input matrix. The dot product between the subset of the input and the kernel is performed, and then all of the values in this product are summed together. This final value becomes a value of our output matrix.

In [0]:
def conv2d(input_mat, kernel_mat):

  # check for square inputs
  if kernel_mat.shape[0] != kernel_mat.shape[1]:
    print("Error: Kernel matrix is not square")
    return
  elif input_mat.shape[0] != input_mat.shape[1]:
    print("Error: Input matrix is not square!")
    return
  else:
    # get the dimensions of the output layer
    n = input_mat.shape[0] - kernel_mat.shape[0] + 1
    m = kernel_mat.shape[0]
  

  output_mat = np.zeros((n, n))

  for i in range(n):
    for k in range(n):
      # multiply by kernel filter
      conv = np.dot(input_mat[i:i+m, k:k+m], kernel_mat)
      # sum all elements
      output_mat[i,k] = np.sum(conv)

  return output_mat

In [3]:
input_mat = np.random.rand(6,6)
kernel_mat = np.random.rand(2,2)
output_mat = conv2d(input_mat, kernel_mat)
print(output_mat)

[[1.17835953 1.17895431 1.30533105 1.41412894 0.94284965]
 [0.91070297 0.65803309 1.14959614 1.21412429 0.92147934]
 [1.44950205 0.79170354 0.70049079 1.1277036  0.97490727]
 [0.98334567 0.82327111 0.64914611 0.97365208 0.60497868]
 [0.92870454 0.72893095 0.98899669 0.91625609 0.76904112]]


# Problem 2

Using only ```numpy```, implement the function ```maxpooling2d```. It takes as input ```input_mat``` and ```s``` and outputs ```output_mat```.
The variables ```input_mat``` and ```output_mat``` are square matrices and ```s``` is an integer.  It should compute the maxpooling operation 
on ```input_mat``` using window of shape ```s``` times ```s```.



# Max Pooling

Max pooling is an operation in which an input matrix and a window size of $s$ by $s$ is specified. The windows iterates throught the input matrix and considers a non overlapping region of $s$ by $s$. The maximum value in that region becomes one of the values in the output matrix. Padding is permitted if the input matrix and window size do not match.

In [0]:
def maxpooling2d(input_mat, s):

  if input_mat.shape[0] != input_mat.shape[1]:
    print("Error: Input matrix is not square!")
    return

  # pad if necessary
  pad = input_mat.shape[0] % s
  matrix = np.pad(input_mat, pad)
  n = matrix.shape[0]
  output_dim = (int(n/s), int(n/s))
  output_mat = np.zeros(output_dim)

  for i in range(0, n, s):
    for k in range(0, n, s):
      x = int(i/s)
      y = int(k/s)
      output_mat[x][y] = np.max(matrix[i:i+s, k:k+s])

  return output_mat

In [5]:
print(maxpooling2d(input_mat, 2))

[[0.74959697 0.65691343 0.72724362]
 [0.95025041 0.72335266 0.9670776 ]
 [0.92180234 0.57058251 0.60806948]]
