<a href="https://colab.research.google.com/github/nspeer12/AI_CAP4630/blob/master/hw4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

### Homework 4

**Problem 1**

Using only ```numpy```, implement the function ```conv2d```.  It takes as input ```input_mat``` and ```kernel_mat``` and outputs ```output_mat```.  All variables 
are square matrices.  It should compute the convolution of ```input_mat``` with the kernel ```kernel_mat``` using valid padding.



kernel slides over the input matrix, performs multiplication for each element, and then adds them up to produce the output

In [0]:
def conv2d(input_mat, kernel_mat):
  # get the dimensions of the output layer
  n = input_mat.shape[0] - kernel_mat.shape[0] + 1
  m = kernel_mat.shape[0]
  print(m)
  output_mat = np.zeros((n, n))

  for i in range(n):
    for k in range(n):
      # multiply by filter
      conv = np.dot(input_mat[i:i+m, k:k+m], kernel_mat)
      # sum all elements
      output_mat[i,k] = np.sum(conv)

  return output_mat

In [62]:
input_mat = np.random.rand(4,4)
kernel_mat = np.random.rand(2,2)
output_mat = conv2d(input_mat, kernel_mat)
print(output_mat)

2
[[1.97233939 1.64429784 2.41160713]
 [3.19981996 2.58710472 2.53681168]
 [2.83504724 1.79239426 1.43536859]]


**Problem 2**

Using only ```numpy```, implement the function ```maxpooling2d```. It takes as input ```input_mat``` and ```s``` and outputs ```output_mat```.
The variables ```input_mat``` and ```output_mat``` are square matrices and ```s``` is an integer.  It should compute the maxpooling operation 
on ```input_mat``` using window of shape ```s``` times ```s```.



**Problem 3**

You will adapt the notebook [using VGG16 conv base for feature extraction, using data augmentation, not using dropout, fine-tuning](https://colab.research.google.com/drive/1F-RWvoxH8MmT7c1UmNy41iuOp-ejiLoF).
You will have to replace the VGG16 conv base by new conv bases. You should not use VGG19.

You should create two notebooks.  Both should use the same conv base, unfreeze the same number of layers of the conv_base, 
but use different classifiers.